/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Project {
  'id' : bigint,
  'title' : string,
  'completionDate' : Time,
  'assignedTo' : [] | [Principal],
  'owner' : Principal,
  'description' : string,
}
export type TaskPriority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface TaskResponse {
  'id' : bigint,
  'title' : string,
  'assignedToLeader' : [] | [UserProfile],
  'assignedTo' : [] | [UserProfile],
  'owner' : UserProfile,
  'completed' : boolean,
  'dueDate' : Time,
  'projectId' : bigint,
  'priority' : TaskPriority,
}
export type Time = bigint;
export interface UserProfile {
  'bio' : string,
  'displayName' : string,
  'avatarInitials' : string,
  'role' : [] | [UserRole],
}
export type UserRole = { 'manager' : null } |
  { 'team_leader' : null } |
  { 'intern' : null } |
  { 'team_member' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'createProject' : ActorMethod<
    [string, string, Time, [] | [Principal]],
    bigint
  >,
  'createTask' : ActorMethod<
    [string, TaskPriority, bigint, [] | [Principal], [] | [Principal], Time],
    undefined
  >,
  'deleteProject' : ActorMethod<[bigint], undefined>,
  'deleteTask' : ActorMethod<[bigint], undefined>,
  'getAllProjects' : ActorMethod<[], Array<Project>>,
  'getAllTasks' : ActorMethod<[], Array<TaskResponse>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getProject' : ActorMethod<[bigint], Project>,
  'getProjectProgress' : ActorMethod<[bigint], [bigint, bigint]>,
  'getProjectTasks' : ActorMethod<[bigint], [] | [Array<TaskResponse>]>,
  'getTask' : ActorMethod<[bigint], TaskResponse>,
  'getTasks' : ActorMethod<[], Array<TaskResponse>>,
  'getUser' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserTasks' : ActorMethod<[Principal], Array<TaskResponse>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setUserRole' : ActorMethod<[UserRole], undefined>,
  'updateProfile' : ActorMethod<[string, string, string], undefined>,
  'updateProject' : ActorMethod<
    [bigint, string, string, Time, [] | [Principal]],
    undefined
  >,
  'updateTask' : ActorMethod<
    [
      bigint,
      string,
      TaskPriority,
      [] | [Principal],
      [] | [Principal],
      Time,
      boolean,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];