/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const TaskPriority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'completionDate' : Time,
  'assignedTo' : IDL.Opt(IDL.Principal),
  'owner' : IDL.Principal,
  'description' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'manager' : IDL.Null,
  'team_leader' : IDL.Null,
  'intern' : IDL.Null,
  'team_member' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'displayName' : IDL.Text,
  'avatarInitials' : IDL.Text,
  'role' : IDL.Opt(UserRole),
});
export const TaskResponse = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'assignedToLeader' : IDL.Opt(UserProfile),
  'assignedTo' : IDL.Opt(UserProfile),
  'owner' : UserProfile,
  'completed' : IDL.Bool,
  'dueDate' : Time,
  'projectId' : IDL.Nat,
  'priority' : TaskPriority,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'createProject' : IDL.Func(
      [IDL.Text, IDL.Text, Time, IDL.Opt(IDL.Principal)],
      [IDL.Nat],
      [],
    ),
  'createTask' : IDL.Func(
      [
        IDL.Text,
        TaskPriority,
        IDL.Nat,
        IDL.Opt(IDL.Principal),
        IDL.Opt(IDL.Principal),
        Time,
      ],
      [],
      [],
    ),
  'deleteProject' : IDL.Func([IDL.Nat], [], []),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getAllTasks' : IDL.Func([], [IDL.Vec(TaskResponse)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getProject' : IDL.Func([IDL.Nat], [Project], ['query']),
  'getProjectProgress' : IDL.Func([IDL.Nat], [IDL.Nat, IDL.Nat], ['query']),
  'getProjectTasks' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(IDL.Vec(TaskResponse))],
      ['query'],
    ),
  'getTask' : IDL.Func([IDL.Nat], [TaskResponse], ['query']),
  'getTasks' : IDL.Func([], [IDL.Vec(TaskResponse)], ['query']),
  'getUser' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserTasks' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(TaskResponse)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setUserRole' : IDL.Func([UserRole], [], []),
  'updateProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateProject' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, Time, IDL.Opt(IDL.Principal)],
      [],
      [],
    ),
  'updateTask' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        TaskPriority,
        IDL.Opt(IDL.Principal),
        IDL.Opt(IDL.Principal),
        Time,
        IDL.Bool,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const TaskPriority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'completionDate' : Time,
    'assignedTo' : IDL.Opt(IDL.Principal),
    'owner' : IDL.Principal,
    'description' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'manager' : IDL.Null,
    'team_leader' : IDL.Null,
    'intern' : IDL.Null,
    'team_member' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'displayName' : IDL.Text,
    'avatarInitials' : IDL.Text,
    'role' : IDL.Opt(UserRole),
  });
  const TaskResponse = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'assignedToLeader' : IDL.Opt(UserProfile),
    'assignedTo' : IDL.Opt(UserProfile),
    'owner' : UserProfile,
    'completed' : IDL.Bool,
    'dueDate' : Time,
    'projectId' : IDL.Nat,
    'priority' : TaskPriority,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'createProject' : IDL.Func(
        [IDL.Text, IDL.Text, Time, IDL.Opt(IDL.Principal)],
        [IDL.Nat],
        [],
      ),
    'createTask' : IDL.Func(
        [
          IDL.Text,
          TaskPriority,
          IDL.Nat,
          IDL.Opt(IDL.Principal),
          IDL.Opt(IDL.Principal),
          Time,
        ],
        [],
        [],
      ),
    'deleteProject' : IDL.Func([IDL.Nat], [], []),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getAllTasks' : IDL.Func([], [IDL.Vec(TaskResponse)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getProject' : IDL.Func([IDL.Nat], [Project], ['query']),
    'getProjectProgress' : IDL.Func([IDL.Nat], [IDL.Nat, IDL.Nat], ['query']),
    'getProjectTasks' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(IDL.Vec(TaskResponse))],
        ['query'],
      ),
    'getTask' : IDL.Func([IDL.Nat], [TaskResponse], ['query']),
    'getTasks' : IDL.Func([], [IDL.Vec(TaskResponse)], ['query']),
    'getUser' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserTasks' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(TaskResponse)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setUserRole' : IDL.Func([UserRole], [], []),
    'updateProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateProject' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, Time, IDL.Opt(IDL.Principal)],
        [],
        [],
      ),
    'updateTask' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          TaskPriority,
          IDL.Opt(IDL.Principal),
          IDL.Opt(IDL.Principal),
          Time,
          IDL.Bool,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };